export const rewriteCopy = {
  step1: {
    intro: "先粘贴原文和改写要求，系统只做去重改写，不改变原文结构。",
    taskTitle: "原文与改写要求",
    taskReady: "已填写",
    taskMissing: "待填写",
    advancedTitle: "高级设置",
    advancedHint: "模型 / API",
    next: "进入结构预览",
  },
  step2: {
    eyebrow: "原文结构预览",
    subtitle: "系统按段落拆分，后续仿写保持结构与推进顺序。",
    structureTitle: "原文段落",
    collapse: "收起",
    expand: "展开",
    collapsedHint: "结构已折叠，点击展开查看每一段原文。",
    empty: "还没有原文结构，请先回到上一步输入原文。",
    copySuccess: "段落已复制。",
    prev: "返回上一步",
    next: "进入生成",
  },
  step3: {
    eyebrow: "生成仿写版本",
    subtitle: "默认生成 1 条，可继续追加 3 条。",
    generateOne: "生成 1 条",
    regenerateOne: "重新生成 1 条",
    generateThree: "再生成 3 条",
    generating: "生成中...",
    hint: "系统会对照原文结构进行改写，字数保持相近。",
    empty: "点击生成后，会在这里出现仿写版本列表。",
    itemBadge: "版本",
    prev: "返回结构预览",
    next: "查看结果",
  },
  step4: {
    eyebrow: "仿写结果",
    generateOne: "生成 1 条",
    regenerateOne: "重新生成 1 条",
    generateThree: "再生成 3 条",
    generating: "生成中...",
    listTitle: "版本列表",
    originalTitle: "仿写正文",
    subtitleTitle: "字幕稿",
    copyScript: "复制正文",
    copySubtitle: "复制字幕",
    copyScriptSuccess: "正文已复制。",
    copySubtitleSuccess: "字幕已复制。",
    empty: "还没有结果，先回到上一步生成。",
    back: "返回生成",
    instructionTitle: "继续优化指令",
    instructionPlaceholder: "比如：语气更像老板讲话，结尾更有行动感。",
    refineButton: "继续优化",
  },
  common: {
    structureCount: "段原文骨架",
    draftCount: "个版本",
  },
} as const;
